###############################################################################
#
# (c) Copyright IBM Corp. 2016
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
###############################################################################

language: c
sudo: false
os: linux

# https://docs.travis-ci.com/user/caching/
cache: ccache

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - libnuma-dev
       - bison
       - numactl

before_script:
  - ulimit -c unlimited
  - make -f run_configure.mk SPEC=linux_x86-64 OMRGLUE=./example/glue
  - export GTEST_FILTER=*NumaSetAffinity
  - numactl --hardware
  - cat /proc/self/cpuset
# Disable the core dump tests as container based builds don't allow setting
# core_pattern and don't have apport installed.  This can be removed when
# apport is available in apt whitelist

script: 
  - make 
  - make test

